/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.chat.ui;

import edu.ijse.chat.connector.ServerConnector;
import edu.ijse.chat.controller.ChatController;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;

/**
 *
 * @author Randula
 */
public class ChatRequest extends javax.swing.JFrame {

    private String sender;
    private String reciever;

    /**
     * Creates new form ChatRequest
     */
    public ChatRequest() {
        initComponents();
    }

    ChatRequest(String sender, String reciever) {
        initComponents();
        this.sender = sender;
        this.reciever = reciever;
        lblFrom.setText(sender);
        lblTo.setText(reciever);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFromTxt = new javax.swing.JLabel();
        lbToTxt = new javax.swing.JLabel();
        lblRequest = new javax.swing.JLabel();
        lblIntro1 = new javax.swing.JLabel();
        lblIntro2 = new javax.swing.JLabel();
        lblIntro3 = new javax.swing.JLabel();
        lblIntro4 = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        btnIgnore = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFromTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFromTxt.setText("From             :");
        getContentPane().add(lblFromTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 30));

        lbToTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbToTxt.setText("To                 :");
        getContentPane().add(lbToTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 30));

        lblRequest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequest.setText("Requesting You To Join With Private Chat Group");
        getContentPane().add(lblRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 310, 30));

        lblIntro1.setText("Chat privately in any time");
        getContentPane().add(lblIntro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 170, 20));

        lblIntro2.setText("This allows you to...");
        getContentPane().add(lblIntro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 170, 20));

        lblIntro3.setText("Keep your conversation safely");
        getContentPane().add(lblIntro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 170, 20));

        lblIntro4.setText("Exchange private documents");
        getContentPane().add(lblIntro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 170, 20));

        lblFrom.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        getContentPane().add(lblFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, 30));

        lblTo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        getContentPane().add(lblTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 140, 30));

        btnIgnore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIgnore.setText("Ignore");
        btnIgnore.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIgnore.setContentAreaFilled(false);
        btnIgnore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgnoreActionPerformed(evt);
            }
        });
        getContentPane().add(btnIgnore, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 100, 30));

        btnConfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirm.setContentAreaFilled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/chat/ui/images/request.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        try {
            ChatController chatController
                    = ServerConnector.getServerConnector().getChatController();
            chatController.sendMessage("COMFIRM", sender,
                    reciever, "JOINED GROUP");
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println(ex.getMessage());
        }
        this.dispose();


    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnIgnoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgnoreActionPerformed

        this.dispose();
        try {
            ChatController chatController
                    = ServerConnector.getServerConnector().getChatController();
            chatController.ignoredRequest(reciever, sender);
        } catch (NotBoundException | MalformedURLException |
                RemoteException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnIgnoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnIgnore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbToTxt;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblFromTxt;
    private javax.swing.JLabel lblIntro1;
    private javax.swing.JLabel lblIntro2;
    private javax.swing.JLabel lblIntro3;
    private javax.swing.JLabel lblIntro4;
    private javax.swing.JLabel lblRequest;
    private javax.swing.JLabel lblTo;
    // End of variables declaration//GEN-END:variables
}
