/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.chat.ui;

import edu.ijse.chat.connector.ServerConnector;
import edu.ijse.chat.controller.ChatController;
import java.awt.Font;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;

/**
 *
 * @author Randula
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        arrangeElements();
    }

    private void arrangeElements() {
        pwtUserPass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        cmbUserType = new javax.swing.JComboBox();
        txtUserName = new javax.swing.JTextField();
        pwtUserPass = new javax.swing.JPasswordField();
        lblLogin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbUserType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbUserType.setForeground(new java.awt.Color(102, 0, 0));
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guest", "Joined" }));
        cmbUserType.setOpaque(false);
        cmbUserType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUserTypeItemStateChanged(evt);
            }
        });
        cmbUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserTypeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 230, 30));

        txtUserName.setBackground(new java.awt.Color(204, 204, 204));
        txtUserName.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(102, 0, 0));
        txtUserName.setText("Your Nick Name Here...");
        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        txtUserName.setOpaque(false);
        txtUserName.setPreferredSize(new java.awt.Dimension(61, 21));
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserNameFocusGained(evt);
            }
        });
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserNameMouseClicked(evt);
            }
        });
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 230, 30));

        pwtUserPass.setBackground(new java.awt.Color(204, 204, 204));
        pwtUserPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pwtUserPass.setForeground(new java.awt.Color(102, 0, 0));
        pwtUserPass.setText("password");
        pwtUserPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        pwtUserPass.setOpaque(false);
        pwtUserPass.setPreferredSize(new java.awt.Dimension(61, 21));
        pwtUserPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwtUserPassFocusGained(evt);
            }
        });
        getContentPane().add(pwtUserPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 230, 30));

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogin.setText("Login");
        lblLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblLogin.setContentAreaFilled(false);
        lblLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLoginActionPerformed(evt);
            }
        });
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 100, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/chat/ui/images/serverSetup.png"))); // NOI18N
        jLabel1.setToolTipText("Set Server Location");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 30, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/chat/ui/images/chatLogin.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUserTypeActionPerformed

    private void cmbUserTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUserTypeItemStateChanged
        if (cmbUserType.getSelectedItem().equals("Guest")) {
            txtUserName.setFont(new Font("Tahoma", 2, 11));
            txtUserName.setText("Your Nick Name Here...");
            pwtUserPass.setVisible(false);
        } else {
            txtUserName.setFont(new Font("Tahoma", 2, 11));
            txtUserName.setText("Your User Name Here...");
            pwtUserPass.setVisible(true);
        }
    }//GEN-LAST:event_cmbUserTypeItemStateChanged

    private void txtUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseClicked


    }//GEN-LAST:event_txtUserNameMouseClicked

    private void txtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusGained
        txtUserName.setText(null);
        txtUserName.setFont(new Font("Tahoma", 0, 12));
    }//GEN-LAST:event_txtUserNameFocusGained

    private void pwtUserPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwtUserPassFocusGained
        pwtUserPass.setText(null);
    }//GEN-LAST:event_pwtUserPassFocusGained

    private void lblLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLoginActionPerformed
        String name = txtUserName.getText();
        String password = String.valueOf(pwtUserPass.getPassword());
        String membership = (String) cmbUserType.getSelectedItem();

        if (membership.equalsIgnoreCase("Guest")) {
            checkGuestAvailability(name, membership);
        } else {
            checkPasswordAvailability(name, password, membership);
        }


    }//GEN-LAST:event_lblLoginActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
//        JOptionPane.showMessageDialog(null, 
//                new EditLocation(), "Setup Server ", 1);

        new LocationFrame().setVisible(true);
       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        pwtUserPass.requestFocusInWindow();
    }//GEN-LAST:event_txtUserNameActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbUserType;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton lblLogin;
    private javax.swing.JPasswordField pwtUserPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
private void checkPasswordAvailability(String name, 
        String password, String membership) {
        try {
            ChatController chatController 
                    = ServerConnector.getServerConnector().getChatController();
            boolean isContains = chatController.getUserList(name);
            boolean isUser = chatController.checkPassword(name, password);

            if (!isContains) {
                if (isUser) {

                    ChatFrame chatFrame = new ChatFrame(name, membership);
                    this.dispose();
                    chatFrame.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Oops! Un-mached user name and password",
                            "Hello User", 1);
                    txtUserName.setText(null);
                }
            } else {
                JOptionPane.showMessageDialog(this, 
                        "Oops! User name unavailable", "Hello User", 1);
                txtUserName.setText(null);
            }

        } catch (NotBoundException | MalformedURLException |
                RemoteException ex) {
            JOptionPane.showMessageDialog(this, 
                    "Server not found...", "Error", 1);
        }

    }

    private void checkGuestAvailability(String name, String membership) {
        try {

            ChatController chatController 
                    = ServerConnector.getServerConnector().getChatController();
            boolean isContains = chatController.getUserList(name);
            if (!isContains) {
                ChatFrame chatFrame = new ChatFrame(name, membership);
                this.dispose();
                chatFrame.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Oops! User name unavailable", "Hello User", 1);
                txtUserName.setText(null);
            }
        } catch (NotBoundException | MalformedURLException | 
                RemoteException ex) {
           JOptionPane.showMessageDialog(this,
                   "Server not found...", "Error", 1);
        }
    }
}
